source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 1
    blur_size = 3
}

animations {
    enabled = true
    bezier = power3Out, 0.22, 1, 0.36, 1
    bezier = power4Out, 0.16, 1, 0.3, 1
    bezier = expoOut, 0.16, 1, 0.3, 1
    animation = fadeIn, 1, 5, power4Out
    animation = fadeOut, 1, 5, power3Out
    animation = inputFieldDots, 1, 2, expoOut
}

label {
    monitor =
    text = ODONDE
    font_size = 28
    font_family = JetBrainsMono Nerd Font
    color = $outer_color
    position = 0, 250
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    color = $font_color
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %-d %B %Y"
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    color = $font_color
    position = 0, 10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_spacing = 0.3
    dots_size = 0.22
    inner_color = $inner_color
    outer_color = $outer_color
    check_color = $check_color
    font_color = $font_color
    fail_color = rgba(255, 0, 0, 0.8)
    fade_on_empty = false
    rounding = 12
    font_family = JetBrainsMono Nerd Font
    placeholder_text = Enter Password
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, -130
    halign = center
    valign = center
}

auth {
    fingerprint {
        enabled = false
    }
}
