# Apple Mac Mini — monitor configuration
# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors: hyprctl monitors

# Straight 1x setup for external display(s)
env = GDK_SCALE,1
monitor=,preferred,auto,1
