gui:
  border: rounded
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - reverse
    optionsTextColor:
      - cyan
git:
  paging:
    colorArg: always
